name: Continuous Delivery

on:
  push:
    branches:
      - prod

env:
  NEXT_PUBLIC_DEPLOYMENT_URL: ${{ secrets.DEPLOYMENT_URL }}

jobs:
  cd:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install

      - name: Build web app
        run: pnpm build

      # Continuous Delivery Pipeline --
      - uses: dswistowski/surge-sh-action@341bcbd
        name: Publish to Surge
        with:
          domain: ${{ secrets.DEPLOYMENT_URL }}
          project: ./out
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
      - uses: 47ng/actions-slack-notify@main
        name: Notify on Slack
        if: always() # Pick up events even if the job fails or is canceled.
        with:
          jobName: Deployment
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
